org: fcandelam
app: aws-nodejs-fcm
service: aws-nodejs-fcm
frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  stage: ${opt:stage, 'dev'}
  environment:
    DYNAMODB_TABLE: ${env:DYNAMODB_TABLE}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - { "Fn::GetAtt": [ "DynamoDBTable", "Arn" ] }

custom:
  dynamodb:
    stages:
      - ${self:provider.stage}
    start:
      docker: true
      port: 8000
      inMemory: true
      migrate: true

functions:
  createEntity:
    handler: src/presentation/controllers/starWarsController.handlerPost
    events:
      - httpApi:
          path: /entity
          method: post
  getEntity:
    handler: src/presentation/controllers/starWarsController.handlerGet
    events:
      - httpApi:
          path: /entity
          method: get

resources:
  Resources:
    DynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: entity_type
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: entity_type
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: entityTypeIndex
            KeySchema:
              - AttributeName: entity_type
                KeyType: HASH
            Projection:
              ProjectionType: ALL

plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline
